version: '3.7'
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: mini-redis
    hostname: mini-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379